import { sendEmail } from './email'

export function generateLifeReviewEmailHTML(
  userName: string,
  reviewText: string,
  date: string
): string {
  const firstName = userName.split(' ')[0] || userName

  // Convert markdown to HTML (basic conversion)
  const htmlContent = reviewText
    .replace(/^## (.*$)/gim, '<h2 style="color: #1e293b; margin: 24px 0 12px 0; font-size: 20px; font-weight: 600;">$1</h2>')
    .replace(/^# (.*$)/gim, '<h1 style="color: #0f172a; margin: 32px 0 16px 0; font-size: 28px; font-weight: 700;">$1</h1>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/^- (.*$)/gim, '<li style="margin: 6px 0;">$1</li>')
    .replace(/\n\n/g, '</p><p style="margin: 12px 0; line-height: 1.6; color: #475569;">')
    .replace(/\n/g, '<br>')

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Your AI Life Review</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      color: #1e293b;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
      background-color: #f8fafc;
    }
    .container {
      background: white;
      border-radius: 12px;
      padding: 40px;
      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }
    .header {
      text-align: center;
      border-bottom: 3px solid #3b82f6;
      padding-bottom: 24px;
      margin-bottom: 32px;
    }
    .header h1 {
      margin: 0;
      color: #0f172a;
      font-size: 32px;
    }
    .header p {
      margin: 8px 0 0 0;
      color: #64748b;
      font-size: 16px;
    }
    .content {
      color: #334155;
    }
    .content h2 {
      color: #1e293b;
      margin: 24px 0 12px 0;
      font-size: 20px;
      font-weight: 600;
      border-left: 4px solid #3b82f6;
      padding-left: 12px;
    }
    .content p {
      margin: 12px 0;
      line-height: 1.6;
      color: #475569;
    }
    .content ul {
      margin: 12px 0;
      padding-left: 24px;
    }
    .content li {
      margin: 6px 0;
      color: #475569;
    }
    .content strong {
      color: #1e293b;
      font-weight: 600;
    }
    .footer {
      margin-top: 40px;
      padding-top: 24px;
      border-top: 1px solid #e2e8f0;
      text-align: center;
      color: #64748b;
      font-size: 14px;
    }
    .cta {
      text-align: center;
      margin: 32px 0;
    }
    .cta a {
      display: inline-block;
      background: #3b82f6;
      color: white;
      padding: 12px 32px;
      border-radius: 8px;
      text-decoration: none;
      font-weight: 600;
      transition: background 0.2s;
    }
    .cta a:hover {
      background: #2563eb;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🧠 Your AI Life Review</h1>
      <p>${date}</p>
      <p>Hey ${firstName}, here's your deep life analysis</p>
    </div>

    <div class="content">
      <p>${htmlContent}</p>
    </div>

    <div class="cta">
      <a href="${process.env.NEXT_PUBLIC_APP_URL}/journal">View in App →</a>
    </div>

    <div class="footer">
      <p>This review was generated by AI based on your journal, habits, spending, and goals.</p>
      <p>Keep tracking your life to get deeper insights over time.</p>
    </div>
  </div>
</body>
</html>
  `.trim()
}

export async function sendLifeReviewEmail(
  userEmail: string,
  userName: string,
  reviewText: string,
  date: string
): Promise<{ success: boolean; error?: string }> {
  const html = generateLifeReviewEmailHTML(userName, reviewText, date)
  
  return await sendEmail({
    to: userEmail,
    subject: `Your AI Life Review – ${date}`,
    html,
  })
}
